from snakemake.utils import min_version

min_version("6.10.0")

configfile: "config/config.yaml"

# Load Samples ----------------------------------------------------------------

import pandas as pd
# getting the samples information (names, path to r1 & r2) from samples.txt
samples_information = pd.read_csv("config/samples.tsv", sep='\t', index_col=False)
# get a list of the sample names
sample_names = list(samples_information['sample_name'])

ORDERS = ["Q0.00","Q1.00","Q1.50","Q2.00","Q3.00","Q4.00"]

#Rules -----------------------------------------------------------------------

rule all:
    input:
        expand("{srr}_1.fastq.gz", srr=sample_names),
        expand("{srr}_2.fastq.gz", srr=sample_names),
        "results/counts/all.tsv",
        "plots/gut_gsea_robust.csv",
        "plots/gut_gsea_top_pos.png",
        "plots/gut_gsea_top_neg.png",
        "plots/gut_gsea_all_pos.png",
        "plots/gut_gsea_all_neg.png"

rule prefetch:
    output:
        ".prefetch/sra/{srr}.sra"
    params:
#        "{srr} --max-size 50GB"
#    log:
#        ".prefetch/sra/{srr}.log"
#    conda:
#        "yamls/sra-tools.yaml"
    shell:
        """
        prefetch {params} && touch {output}
        """
#prefetch {params} > {log} 2>&1 && touch {output}

rule fastqdump:
    input:
        ".prefetch/sra/{srr}.sra"
    output:
#        touch("done__{srr}_dump")
        touch("{srr}_1.fastq.gz"),
        touch("{srr}_2.fastq.gz")
    params:
        args = "--split-files --gzip",
        id_srr = "{srr}"
#    log:
#        "{srr}.log"
#    conda:
#        "yamls/sra-tools.yaml"
    shell:
        """
        fastq-dump {params.args} {params.id_srr}
        """
#        fasterq-dump --split-files {params.args} {params.id_srr} > {log} 2>&1



#declare https://github.com/snakemake-workflows/rna-seq-star-deseq2 as a module
module rna_seq_star_deseq2:
    snakefile:
#        github("snakemake-workflows/rna-seq-star-deseq2", path="workf"low/Snakefile", tag="v1.2.0")
        github("plycrsk/rna-seq-star-deseq2", path="workflow/Snakefile", branch="master")
    config:
        config

#use all rules from https://github.com/snakemake-workflows/rna-seq-star-deseq2
use rule * from rna_seq_star_deseq2

#configfile: "config.yaml"

rule DESeq:
    input:
        "results/counts/all.tsv",
        "raw_data/meta_data_{diversity}.csv"
    output:
        "data/DESeq/{diversity}.csv"
    script:
        "scripts/1.DESeq2_Analysis.R"

rule GSEA:
    input:
        "data/DESeq/{diversity}.csv",
        "raw_data/killifish_human_ortho.csv"
    output:
        "data/GSEA/{diversity}.rda",
        "data/GSEA/{diversity}.csv"
    script:
        "scripts/2.GSEA_Analysis.R"

rule Immune_Term_Reduction:
    input:
        "data/GSEA/{diversity}.csv"
    output:
        "data/GSEA_reduction/{diversity}.csv"
    script:
        "scripts/3.GO_Term_Reduction.R"

rule GSEA_plots:
    input:
        expand("data/GSEA_reduction/{diversity}.csv", diversity=ORDERS)
    output:
        robust = "plots/gut_gsea_robust.csv",
        top_pos = "plots/gut_gsea_top_pos.png",
        top_neg = "plots/gut_gsea_top_neg.png",
        all_pos = "plots/gut_gsea_all_pos.png",
        all_neg = "plots/gut_gsea_all_neg.png"
    script:
        "scripts/4.Make_gsea_plots.R"
