from snakemake.utils import min_version

min_version("6.10.0")

configfile: "config/config.yaml"

rule Units_file:
    input:
        "config/samples.tsv"
    output:
        "config/srr_accession.txt",
        "config/units.tsv"
    script:
        "scripts/2.Units_file.R"

rule sra_download:
    input:
        "config/samples.tsv"
    shell:
        "fastq-dump --split-files {input} {output}"




#declare https://github.com/snakemake-workflows/rna-seq-star-deseq2 as a module
#module rna_seq_star_deseq2:
#    snakefile:
#        github("snakemake-workflows/rna-seq-star-deseq2", path="workflow/Snakefile", tag="v1.2.0")
#    config:
#        config


#use all rules from https://github.com/snakemake-workflows/rna-seq-star-deseq2
#use rule * from rna_seq_star_deseq2
