##############################################################################
## SNAKEFILE
## PIPELINE: IgSeq Functional Analysis
## SUB-PIPELINE: Pre-processing
## AUTHOR: Sam Kean
##############################################################################

GSEA:
  seed = 888888
